<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.smsHelper' shared service.

return $this->services['app.smsHelper'] = new \AppBundle\Services\SmsHelper();
