<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Conductas;

/**
 * ConductasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConductasRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Función que devuelve un array con las conductas indexadas por el tipo
     * @return array Array con las conductas indexadas por el tipo
     */
    public function getConductasOption()
    {
        $conductas = $this->findAll();
        $arrConductas = [];
        /** @var Conductas $conducta */
        foreach ($conductas as $conducta) {
            $arrConductas[$conducta->getTipo()][] = $conducta->getNombreAndPuntos();
        }
        return $arrConductas;
    }

    /**
     * Función que devuelve las conductas
     * @return array
     */
    public function getConductas()
    {
        $qb = $this->getEntityManager()->createQuery(
            'SELECT c.id,c.conducta,c.puntos
           FROM AppBundle\Entity\Conductas c'
        );

        return $qb->getResult();
    }

}
