<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Noticias;

/**
 * NoticiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Función que devuelve todas las noticias
     * @return array
     */
    public function getNoticias()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT n
             FROM AppBundle\Entity\Noticias n
             ORDER BY n.fecha desc'
        );

        return $query->getResult();

    }
    /**
     * Función que devuelve noticia para el alumno
     * @return array
     */
    public function getNoticiasCurso($curso,$puntos)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT n
             FROM AppBundle\Entity\Noticias n
             WHERE n.idCurso = :curso and n.puntos = :puntos ORDER BY n.fecha desc'
        );
        $query->setParameter(':curso', $curso);
        $query->setParameter(':puntos', $puntos);
        $query->setMaxResults(1);

        return $query->getResult();

    }
}
