<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Noticias;

/**
 * NoticiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Función que devuelve todas las noticias
     * @return array
     */
    public function getNoticias()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT n
             FROM AppBundle\Entity\Noticias n
             ORDER BY n.fecha desc'
        );

        return $query->getResult();

    }
    /**
     * Función que devuelve noticia para el alumno
     * @return array
     */
    public function getNoticiasCurso($curso,$puntos)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT n
             FROM AppBundle\Entity\Noticias n
             WHERE n.idCurso = :curso and n.puntos = :puntos ORDER BY n.fecha desc'
        );
        $query->setParameter(':curso', $curso);
        $query->setParameter(':puntos', $puntos);
        $query->setMaxResults(1);

        return $query->getResult();

    }

    /**
     * Función que realiza un update en noticias
     * @return array
     */
    public function updateNoticias($id,$curso,$puntos,$fechaI,$fechaF,$texto)
    {
            $query = $this->getEntityManager()->createQuery(
                'UPDATE AppBundle\Entity\noticias n 
                SET n.fechaFinal= :fechaF, n.fechaInicio= :fechaI, n.idCurso=:curso, n.puntos=:puntos, n.noticia_texto=:texto 
                where n.id= :id ');

            $query->setParameter(':id', $id);
            $query->setParameter(':curso', $curso);
            $query->setParameter(':puntos', $puntos);
            $query->setParameter(':fechaI', $fechaI);
            $query->setParameter(':fechaF', $fechaF);
            $query->setParameter(':texto', $texto);
        return $query->getResult();

    }
    /**
     * Función que devuelve noticia segun el id
     * @return array
     */
    public function getNoticia($id)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT n
             FROM AppBundle\Entity\Noticias n 
             WHERE n.id = :id');

        $query->setParameter(':id', $id);
        return $query->getResult();

    }


}
